// ============================================================
// APHANTASIA — Design DNA Type System
// ============================================================
// Every project gets a unique DesignDNA — a bespoke set of
// design tokens generated by AI from the user's context.
// This is NOT a preset. It's a per-project design direction.
// ============================================================

// ---------------------------------------------------------------------------
// Sub-types
// ---------------------------------------------------------------------------

export interface DNAPalette {
  background: string;        // e.g. "#0C0C0C"
  foreground: string;        // e.g. "#EBEBEB"
  accent: string;            // e.g. "#14B8A6"
  accentForeground: string;  // e.g. "#FFFFFF"
  muted: string;             // e.g. "#1A1A1A"
  mutedForeground: string;   // e.g. "#8A8A9A"
  card: string;              // e.g. "#111111"
  cardForeground: string;    // e.g. "#D4D4D4"
  border: string;            // e.g. "rgba(255,255,255,0.08)"
}

export interface DNATypography {
  headingFamily: string;           // e.g. "Satoshi"
  bodyFamily: string;              // e.g. "DM Sans"
  headingWeight: number;           // e.g. 700
  headingWeightLight?: number;     // e.g. 300 — secondary weight for split-weight headlines (expressive strategy only)
  headingLetterSpacing: string;    // e.g. "-0.03em"
  scale: "dramatic" | "balanced" | "compact";
}

export type SpacingDensity = "spacious" | "balanced" | "tight";

export interface DNASpacing {
  density: SpacingDensity;
  sectionPadding: string;    // e.g. "clamp(80px, 12vw, 140px)"
  contentMaxWidth: string;   // e.g. "1100px"
  cardPadding: string;       // e.g. "32px"
  gridGap: string;           // e.g. "24px"
}

export type SurfaceStyle =
  | "flat"
  | "gradient-mesh"
  | "grain"
  | "accent-wash"
  | "radial-glow";

export type SectionStyle = "alternating" | "uniform" | "contrasting";

export type CardSurface =
  | "elevated"
  | "bordered"
  | "glass"
  | "flat"
  | "accent-top";

export interface DNASurfaces {
  hero: SurfaceStyle;
  sections: SectionStyle;
  cards: CardSurface;
}

export type DecorativeStyle =
  | "geometric"
  | "organic"
  | "minimal"
  | "editorial"
  | "grid-overlay"
  | "gradient-blobs";

export type DecorativeIntensity = "subtle" | "moderate" | "bold";

export interface DNADecorative {
  style: DecorativeStyle;
  intensity: DecorativeIntensity;
}

export type MotionLevel = "none" | "subtle" | "expressive";

export type EntranceAnimation =
  | "fade-up"
  | "fade-in"
  | "slide-in"
  | "scale-up"
  | "none";

export type HoverAnimation =
  | "lift"
  | "glow"
  | "scale"
  | "border-accent"
  | "none";

export interface DNAMotion {
  level: MotionLevel;
  entrance: EntranceAnimation;
  hover: HoverAnimation;
  staggerDelay: string;  // e.g. "0.08s"
  duration: string;      // e.g. "0.6s"
}

export type ButtonStyle = "solid" | "outline" | "ghost" | "gradient";
export type ButtonSize = "compact" | "standard" | "large";

export interface DNAButtons {
  radius: string;     // "0px" (sharp) to "9999px" (pill)
  style: ButtonStyle;
  size: ButtonSize;
}

export type ImageTreatment = "natural" | "duotone" | "grayscale" | "saturated";
export type ImageFrame = "none" | "browser" | "phone" | "shadow";

export interface DNAImages {
  radius: string;
  treatment: ImageTreatment;
  frame: ImageFrame;
}

// ---------------------------------------------------------------------------
// Main DesignDNA interface
// ---------------------------------------------------------------------------

export interface DesignDNA {
  palette: DNAPalette;
  typography: DNATypography;
  spacing: DNASpacing;
  surfaces: DNASurfaces;
  decorative: DNADecorative;
  motion: DNAMotion;
  buttons: DNAButtons;
  images: DNAImages;
  moodSlug: string;
}

// ---------------------------------------------------------------------------
// Default DNA — the "little black dress"
// ---------------------------------------------------------------------------
// Beautiful at zero context. Professional enough to deploy as-is.
// Dark, clean, modern — not generic wireframe gray.
// ---------------------------------------------------------------------------

export const DEFAULT_DNA: DesignDNA = {
  palette: {
    background: "#0C0C0C",
    foreground: "#EBEBEB",
    accent: "#14B8A6",
    accentForeground: "#FFFFFF",
    muted: "#1A1A1A",
    mutedForeground: "#8A8A9A",
    card: "#111111",
    cardForeground: "#D4D4D4",
    border: "rgba(255,255,255,0.08)",
  },
  typography: {
    headingFamily: "Satoshi",
    bodyFamily: "DM Sans",
    headingWeight: 700,
    headingLetterSpacing: "-0.03em",
    scale: "balanced",
  },
  spacing: {
    density: "spacious",
    sectionPadding: "clamp(80px, 10vw, 120px)",
    contentMaxWidth: "1100px",
    cardPadding: "32px",
    gridGap: "24px",
  },
  surfaces: {
    hero: "flat",
    sections: "uniform",
    cards: "bordered",
  },
  decorative: {
    style: "minimal",
    intensity: "subtle",
  },
  motion: {
    level: "subtle",
    entrance: "fade-up",
    hover: "lift",
    staggerDelay: "0.08s",
    duration: "0.6s",
  },
  buttons: {
    radius: "8px",
    style: "solid",
    size: "standard",
  },
  images: {
    radius: "12px",
    treatment: "natural",
    frame: "none",
  },
  moodSlug: "dark-minimal-saas",
};

// ---------------------------------------------------------------------------
// DNA source tracking
// ---------------------------------------------------------------------------

export type DNASource = "default" | "generated" | "reference" | "manual";
