// ============================================================
// Aphantasia/System — Full Next.js Project Export
// ============================================================

import type { Project, SpecNode, ComponentType, Screen } from "../types";
import { getUsedComponentTypes } from "../codegen";

export interface ExportedProject {
  files: Record<string, string>;
  dependencies: Record<string, string>;
}

// ── Token → CSS variable name ───────────────────────────────

function tokenToVar(key: string): string {
  return `--${key.replace(/\./g, "-")}`;
}

function tokenToTw(key: string): string {
  return `var(${tokenToVar(key)})`;
}

// ── Generate globals.css ────────────────────────────────────

function generateGlobalsCss(tokens: Record<string, string>, darkTokens: Record<string, string>): string {
  const lightVars = Object.entries(tokens)
    .map(([k, v]) => `  ${tokenToVar(k)}: ${v};`)
    .join("\n");
  const darkVars = Object.entries(darkTokens)
    .filter(([k, v]) => v !== tokens[k])
    .map(([k, v]) => `  ${tokenToVar(k)}: ${v};`)
    .join("\n");

  return `@import "tailwindcss";

:root {
${lightVars}
}
${darkVars ? `\n.dark {\n${darkVars}\n}` : ""}

body {
  font-family: var(--font-sans);
  background: var(--bg-page);
  color: var(--text-primary);
}
`;
}

// ── Generate layout.tsx ─────────────────────────────────────

function generateLayout(): string {
  return `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Aphantasia Export",
  description: "Generated by Aphantasia/System",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.variable}>{children}</body>
    </html>
  );
}
`;
}

// ── Screen → route slug ─────────────────────────────────────

function screenSlug(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

// ── SpecNode → JSX string ───────────────────────────────────

function nodeToJSX(node: SpecNode, indent: number, usedImports: Set<string>): string {
  const pad = "  ".repeat(indent);
  const p = node.props as Record<string, unknown>;

  if (node.type === "__root") {
    return node.children.map(c => nodeToJSX(c, indent, usedImports)).join("\n");
  }

  if (node.type === "__row") {
    const gap = (p.gap as string) ?? "1.5rem";
    const children = node.children.map(c => nodeToJSX(c, indent + 1, usedImports)).join("\n");
    return `${pad}<div className="flex gap-6 px-12">\n${children}\n${pad}</div>`;
  }

  if (node.type === "Nav") {
    const brand = (p.brand as string) ?? "Brand";
    return `${pad}<header className="flex items-center px-6 h-14 border-b border-[${tokenToTw("border.default")}]">
${pad}  <span className="font-bold text-base">${brand}</span>
${pad}  <div className="flex-1" />
${pad}  <nav className="flex gap-6 text-sm text-[${tokenToTw("text.secondary")}]">
${pad}    <a href="#">Features</a>
${pad}    <a href="#">Pricing</a>
${pad}    <a href="#">Docs</a>
${pad}  </nav>
${pad}  <button className="ml-6 px-3.5 py-1.5 rounded-md bg-[${tokenToTw("brand.primary")}] text-[${tokenToTw("brand.primary.fg")}] text-sm font-medium">Sign Up</button>
${pad}</header>`;
  }

  if (node.type === "Section") {
    const align = p.align === "center" ? " items-center text-center" : "";
    const children = node.children.map(c => nodeToJSX(c, indent + 1, usedImports)).join("\n");
    return `${pad}<section className="flex flex-col gap-4 py-12 px-12${align}">\n${children}\n${pad}</section>`;
  }

  if (node.type === "Card") {
    usedImports.add("Card");
    const children = node.children.map(c => nodeToJSX(c, indent + 2, usedImports)).join("\n");
    return `${pad}<div className="flex-1 rounded-xl border border-[${tokenToTw("border.default")}] bg-[${tokenToTw("bg.card")}] p-5 shadow-md flex flex-col gap-3">\n${children}\n${pad}</div>`;
  }

  if (node.type === "Button") {
    usedImports.add("Button");
    const label = (p.label as string) ?? "Button";
    const variant = node.variant ?? "primary";
    const size = p.size === "lg" ? ' className="w-full"' : "";
    return `${pad}<Button variant="${variant}"${size}>${label}</Button>`;
  }

  if (node.type === "Text") {
    const content = (p.content as string) ?? "";
    const tags: Record<string, string> = { h1: "h1", h2: "h2", h3: "h3", p: "p", caption: "p", label: "span" };
    const tag = tags[node.variant ?? "p"] ?? "p";
    const classes: Record<string, string> = {
      h1: 'className="text-4xl font-extrabold tracking-tight"',
      h2: 'className="text-2xl font-bold tracking-tight"',
      h3: 'className="text-xl font-semibold"',
      p: 'className="text-base leading-relaxed text-[' + tokenToTw("text.secondary") + ']"',
      caption: 'className="text-sm text-[' + tokenToTw("text.tertiary") + ']"',
      label: 'className="text-sm font-medium"',
    };
    const cls = classes[node.variant ?? "p"] ?? "";
    return `${pad}<${tag} ${cls}>${content}</${tag}>`;
  }

  if (node.type === "Badge") {
    usedImports.add("Badge");
    return `${pad}<Badge variant="${node.variant ?? "default"}">${(p.label as string) ?? "Badge"}</Badge>`;
  }

  if (node.type === "Input") {
    usedImports.add("Input");
    const label = p.label as string;
    const placeholder = (p.placeholder as string) ?? "";
    if (label) {
      return `${pad}<div className="flex flex-col gap-1.5">\n${pad}  <label className="text-sm font-medium">${label}</label>\n${pad}  <Input type="${node.variant ?? "text"}" placeholder="${placeholder}" />\n${pad}</div>`;
    }
    return `${pad}<Input type="${node.variant ?? "text"}" placeholder="${placeholder}" />`;
  }

  if (node.type === "Avatar") {
    return `${pad}<div className="w-9 h-9 rounded-full bg-[${tokenToTw("bg.muted")}] flex items-center justify-center text-sm font-semibold text-[${tokenToTw("text.secondary")}]">${(p.initials as string) ?? "?"}</div>`;
  }

  if (node.type === "Separator") {
    return `${pad}<hr className="border-[${tokenToTw("border.default")}]" />`;
  }

  if (node.type === "Image") {
    return `${pad}<div className="aspect-video bg-gradient-to-br from-[${tokenToTw("bg.muted")}] to-[${tokenToTw("border.default")}] rounded-lg flex items-center justify-center text-sm text-[${tokenToTw("text.tertiary")}]">${(p.alt as string) ?? "Image"}</div>`;
  }

  if (node.type === "Toggle") {
    return `${pad}<label className="flex items-center gap-2.5 cursor-pointer">\n${pad}  <input type="checkbox" className="sr-only peer" />\n${pad}  <div className="w-11 h-6 rounded-full bg-[${tokenToTw("border.default")}] peer-checked:bg-[${tokenToTw("brand.primary")}] relative after:content-[''] after:absolute after:top-0.5 after:left-0.5 after:w-5 after:h-5 after:bg-white after:rounded-full after:transition peer-checked:after:translate-x-5" />\n${pad}  <span className="text-sm">${(p.label as string) ?? "Toggle"}</span>\n${pad}</label>`;
  }

  if (node.type === "Alert") {
    const colors: Record<string, string> = { info: "blue", success: "green", warning: "amber", error: "red" };
    const c = colors[node.variant ?? "info"] ?? "blue";
    return `${pad}<div className="flex flex-col gap-1 p-3 rounded-md border-l-4 border-${c}-500 bg-${c}-50">\n${pad}  <span className="font-semibold text-${c}-700">${(p.title as string) ?? "Alert"}</span>\n${pad}  <span className="text-sm text-${c}-600">${(p.description as string) ?? ""}</span>\n${pad}</div>`;
  }

  if (node.type === "Table") {
    const headers = (p.headers as string[]) ?? ["Col 1", "Col 2"];
    const rows = (p.rows as string[][]) ?? [];
    const ths = headers.map(h => `${pad}        <th className="px-3 py-2 text-left font-semibold border-b-2 border-[${tokenToTw("border.default")}]">${h}</th>`).join("\n");
    const trs = rows.map((row, ri) => {
      const tds = row.map(cell => `${pad}        <td className="px-3 py-2 border-b border-[${tokenToTw("border.default")}]">${cell}</td>`).join("\n");
      return `${pad}      <tr${node.variant === "striped" && ri % 2 === 1 ? ` className="bg-[${tokenToTw("bg.muted")}]"` : ""}>\n${tds}\n${pad}      </tr>`;
    }).join("\n");
    return `${pad}<table className="w-full text-sm">\n${pad}  <thead>\n${pad}    <tr>\n${ths}\n${pad}    </tr>\n${pad}  </thead>\n${pad}  <tbody>\n${trs}\n${pad}  </tbody>\n${pad}</table>`;
  }

  if (node.type === "Footer") {
    const children = node.children.map(c => nodeToJSX(c, indent + 1, usedImports)).join("\n");
    return `${pad}<footer className="bg-[${tokenToTw("bg.muted")}] px-8 py-6 flex flex-wrap gap-4 items-center${node.variant === "simple" ? " justify-center" : ""}">\n${children}\n${pad}</footer>`;
  }

  if (node.type === "Form") {
    const children = node.children.map(c => nodeToJSX(c, indent + 1, usedImports)).join("\n");
    return `${pad}<form className="flex flex-col gap-3 max-w-md">\n${children}\n${pad}</form>`;
  }

  if (node.type === "Progress") {
    const pct = (p.percentage as number) ?? 50;
    return `${pad}<div className="flex flex-col gap-1.5">\n${pad}  <div className="flex justify-between text-sm"><span>${(p.label as string) ?? "Progress"}</span><span className="font-semibold">${pct}%</span></div>\n${pad}  <div className="h-2 rounded-full bg-[${tokenToTw("bg.muted")}] overflow-hidden"><div className="h-full rounded-full bg-[${tokenToTw("brand.primary")}]" style={{ width: "${pct}%" }} /></div>\n${pad}</div>`;
  }

  if (node.type === "Breadcrumb") {
    const items = (p.items as string[]) ?? ["Home"];
    const spans = items.map((item, i) => i === items.length - 1 ? `<span className="font-medium">${item}</span>` : `<a href="#" className="text-[${tokenToTw("text.secondary")}] hover:underline">${item}</a>`);
    return `${pad}<nav className="flex items-center gap-1.5 text-sm">${spans.join(` <span className="text-[${tokenToTw("text.tertiary")}]">/</span> `)}</nav>`;
  }

  // Fallback for other types: render children in a div
  const children = node.children.map(c => nodeToJSX(c, indent + 1, usedImports)).join("\n");
  if (children) return `${pad}<div>\n${children}\n${pad}</div>`;
  return `${pad}<div>{/* ${node.type} */}</div>`;
}

// ── Generate page component ─────────────────────────────────

function generatePage(screen: Screen, usedImports: Set<string>): string {
  const body = nodeToJSX(screen.root, 2, usedImports);

  const imports: string[] = [];
  if (usedImports.has("Button")) imports.push('import { Button } from "@/components/ui/button";');
  if (usedImports.has("Badge")) imports.push('import { Badge } from "@/components/ui/badge";');
  if (usedImports.has("Input")) imports.push('import { Input } from "@/components/ui/input";');
  if (usedImports.has("Card")) imports.push('import { Card } from "@/components/ui/card";');

  return `${imports.length ? imports.join("\n") + "\n\n" : ""}export default function ${screen.name.replace(/[^a-zA-Z0-9]/g, "")}Page() {
  return (
    <div className="min-h-screen bg-[var(--bg-page)]">
${body}
    </div>
  );
}
`;
}

// ── shadcn/ui component templates ───────────────────────────

function buttonComponent(): string {
  return `import * as React from "react";

type ButtonVariant = "primary" | "secondary" | "outline" | "ghost" | "destructive";

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
}

const variantClasses: Record<ButtonVariant, string> = {
  primary: "bg-[var(--brand-primary)] text-[var(--brand-primary-fg)] hover:opacity-90",
  secondary: "bg-[var(--bg-muted)] text-[var(--text-primary)] hover:opacity-90",
  outline: "border border-[var(--border-default)] text-[var(--text-primary)] hover:bg-[var(--bg-muted)]",
  ghost: "text-[var(--text-primary)] hover:bg-[var(--bg-muted)]",
  destructive: "bg-[var(--brand-destructive)] text-white hover:opacity-90",
};

export function Button({ variant = "primary", className = "", children, ...props }: ButtonProps) {
  return (
    <button
      className={\`inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors \${variantClasses[variant]} \${className}\`}
      {...props}
    >
      {children}
    </button>
  );
}
`;
}

function inputComponent(): string {
  return `import * as React from "react";

interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {}

export function Input({ className = "", ...props }: InputProps) {
  return (
    <input
      className={\`flex h-10 w-full rounded-md border border-[var(--border-default)] bg-[var(--bg-page)] px-3 py-2 text-sm placeholder:text-[var(--text-tertiary)] focus:outline-none focus:ring-2 focus:ring-[var(--border-focus)] \${className}\`}
      {...props}
    />
  );
}
`;
}

function badgeComponent(): string {
  return `import * as React from "react";

type BadgeVariant = "default" | "secondary" | "outline" | "destructive";

interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: BadgeVariant;
}

const variantClasses: Record<BadgeVariant, string> = {
  default: "bg-[var(--brand-primary)] text-[var(--brand-primary-fg)]",
  secondary: "bg-[var(--bg-muted)] text-[var(--text-primary)]",
  outline: "border border-[var(--border-default)] text-[var(--text-primary)]",
  destructive: "bg-[var(--brand-destructive)] text-white",
};

export function Badge({ variant = "default", className = "", children, ...props }: BadgeProps) {
  return (
    <span
      className={\`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium \${variantClasses[variant]} \${className}\`}
      {...props}
    >
      {children}
    </span>
  );
}
`;
}

function cardComponent(): string {
  return `import * as React from "react";

export function Card({ className = "", children, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div className={\`rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] shadow-md \${className}\`} {...props}>
      {children}
    </div>
  );
}
`;
}

// ── Main export function ────────────────────────────────────

export function generateNextJSProject(
  project: Project,
  tokens: Record<string, string>,
  darkTokens: Record<string, string>,
): ExportedProject {
  const files: Record<string, string> = {};
  const projectName = screenSlug(project.screens[0]?.name ?? "project");

  // Collect all used component types across all screens
  const allUsed = new Set<ComponentType>();
  for (const screen of project.screens) {
    for (const t of getUsedComponentTypes(screen.root)) allUsed.add(t);
  }

  // package.json
  const dependencies: Record<string, string> = {
    next: "^15.0.0",
    react: "^19.0.0",
    "react-dom": "^19.0.0",
    tailwindcss: "^4.0.0",
    "@tailwindcss/postcss": "^4.0.0",
  };
  const devDependencies: Record<string, string> = {
    typescript: "^5.0.0",
    "@types/react": "^19.0.0",
    "@types/node": "^22.0.0",
  };

  files["package.json"] = JSON.stringify({
    name: projectName,
    version: "0.1.0",
    private: true,
    scripts: { dev: "next dev", build: "next build", start: "next start" },
    dependencies,
    devDependencies,
  }, null, 2);

  // tsconfig.json
  files["tsconfig.json"] = JSON.stringify({
    compilerOptions: {
      target: "ES2017",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: { "@/*": ["./src/*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  }, null, 2);

  // next.config.ts
  files["next.config.ts"] = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;

  // postcss.config.mjs
  files["postcss.config.mjs"] = `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
`;

  // globals.css
  files["src/app/globals.css"] = generateGlobalsCss(tokens, darkTokens);

  // layout.tsx
  files["src/app/layout.tsx"] = generateLayout();

  // shadcn/ui components (only those actually used)
  const uiImports = new Set<string>();
  // Pre-scan all screens to find which UI components are needed
  for (const screen of project.screens) {
    const screenImports = new Set<string>();
    nodeToJSX(screen.root, 0, screenImports);
    for (const imp of screenImports) uiImports.add(imp);
  }

  if (uiImports.has("Button")) files["src/components/ui/button.tsx"] = buttonComponent();
  if (uiImports.has("Input")) files["src/components/ui/input.tsx"] = inputComponent();
  if (uiImports.has("Badge")) files["src/components/ui/badge.tsx"] = badgeComponent();
  if (uiImports.has("Card")) files["src/components/ui/card.tsx"] = cardComponent();

  // Pages — first screen is the index, rest get their own routes
  for (let i = 0; i < project.screens.length; i++) {
    const screen = project.screens[i];
    const pageImports = new Set<string>();
    const content = generatePage(screen, pageImports);
    const path = i === 0 ? "src/app/page.tsx" : `src/app/${screenSlug(screen.name)}/page.tsx`;
    files[path] = content;
  }

  return { files, dependencies };
}
